# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 20
  - name: Research
    url: research/
    weight: 30
  - name: News
    url: /news
    weight: 40
  - name: Posts
    url: '/post'
    weight: 50
  # - name: Projects
  #   url: projects/
  #   weight: 60
  # - name: Talks
  #   url: /talks
  #   weight: 70
