# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Researcher named Orjan Ameye at the University of Konstanz.'
    twitter: 'OrjanAmeye'
  analytics:
    google_analytics: 'G-CPHDFQL1QQ'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'Bhl7mMlFZKqx2U0A2Ob6-eSffTc38xtZyQSY-WyF4xA'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    highlight_active_link: true
    logo:
      text: "Orjan Ameye"

# Site footer
# footer:
#   block: minimal
#   copyright:
#     notice: '© {year} Me. This work is licensed under {license}'
#     license:
#       enable: true
#       allow_derivatives: false
#       share_alike: true
#       allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/oameye/website'
    content_dir: content
    branch: main
