[project]
name = "phys-rev-a-56-4175-1997"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.4.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "qutip>=5.2.0",
    "scipy>=1.16.0",
]
