name: Merge to main workflows

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4
      with:
        submodules: true  # This fetches the submodules
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Update Hugo Modules
      run: hugo mod tidy

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install node modules
      run: |
        hugo mod npm pack
        npm install

    - name: Build
      run: hugo --minify

    # Deploy to the submodule repository
    - name: Deploy to submodule
      run: |
        cd public
        git add .
        git commit -m "Update site $(date)" || exit 0
        git push origin maina